name = "my-site"
compatibility_date = "2024-09-23"
main = "./worker.js"

[assets]
directory = "./dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "my-site-counter"
database_id = "6fd23f49-2df1-498e-99d9-f79ee1dda5fd"
